name: Build

on:
  push:
    branches:
      - 'master'
      - 'sandbox'
      
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean package